---
title: "Lung-resident immune cells"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Welcome to the project website. 

This project is about using functional profiling of lung immune cells to better understand the genetics of asthma and allergy diseases.

## Introduction
TBD

## Literature reviews 

## Results

### characterize cell populations 

[Detecting GATA3+ subpopulations](DEG_analysis_Tsub.html)

### Heritability enrichment vs Differential peak analyses

[test heritability enrichment for lung immune subsets](h2g_enrichment_u19.html)

[converge enrichment and differnetial CA results](lung_specific_peaks_vs_DA_analyses.html)

### Topic analysis

Topic QC

- [examine batch effects for the matched RNA/ATAC-seq datasets](identify_batch_effects_multiomics.html)
- [examine batch effects for the full ATAC-seq](identify_batch_effects_full_atac.html)

Topic models on scRNA-seq data 

- [identify topics with different proportions between tissue](cross_tissue_DE_u19_fastTopics.html)
- [test topic enrichment for genetic risks using MAGMA](gene_set_analysis_for_RNA_topics.html) 
- [test motif enrichment for topic-specific genes](U19_motif_analysis.html)  

Topic models on lung scATAC-seq data

- [identify topics with high proportion in cases](u19_lung_atac_fastTopics.html)

### GRN analysis
[test motif enrichment for TF targets from GRN](identify_TFs_with_immune_function.html)


### Linking to asthma genetics

[identify cell-types with open chromatin in asthma fine-mapped regions](variants_to_function_u19.html)

[differential analyses at genome-wide and specific loci](differential_peak_analysis_u19.html)

[understand why lung-specific peaks not show differential accessibility](lung_specific_peaks_vs_DA_analyses.html)
### Slides download

### Notes